# Generated by Django 3.1.7 on 2021-03-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210324_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postdata',
            name='ico',
            field=models.CharField(max_length=8),
        ),
    ]
